name: 'ci'

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE'
      - 'README.md'
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE'
      - 'README.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ci:
    uses: './.github/workflows/reusable-workflow-ci.yml'
    with: 
      path: '.'
