on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ci-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: npm
          cache-dependency-path: ${{ inputs.path }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.path }}

      - name: Test
        run: npm test --if-present
        working-directory: ${{ inputs.path }}

      - name: Build
        run: npm run build --if-present
        working-directory: ${{ inputs.path }}

      - name: Check style
        run: npm run style-check --if-present
        working-directory: ${{ inputs.path }}
        if: github.event_name == 'pull_request'
